---
# tasks file for gce

- name: Create GCE instances
  local_action:
    module: gce
    instance_names: "{{ item.names }}"
    machine_type: "{{ item.type }}"
    image: "{{ item.image }}"
    zone: "{{ item.zone }}"
    tags: "{{ item.tags }}"
    service_account_email: "{{ service_account_email }}"
    pem_file: "{{ pem_file }}"
    project_id: "{{ project_id }}"
  register: gce
  with_items: instances

#- debug: msg=gce.stdout_lines

- name: Wait for SSH to be available
  local_action: wait_for host={{ item.1.public_ip }} port=22 delay=20 timeout=30 state=started
  with_subelements: 
    - gce.results
    - instance_data
  when: item.0.changed
